version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: ali
      POSTGRES_DB: dev-track
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
